# """
# AI summarization - supports DeepSeek / OpenAI / any OpenAI-compatible API.
# """

# import os
# import requests


# SYSTEM_PROMPT = """你是一个专业的 AI 行业资讯编辑。你的任务是将收集到的原始 AI 资讯整理成一份高质量的每日简报。

# 要求：
# 1. 从提供的原始内容中筛选出最有价值的 10-15 条资讯
# 2. 去除重复和低质量内容
# 3. 每条资讯必须保留原文链接，不能省略 URL
# 4. 按类别分组：📰 行业新闻 / 📄 重要论文 / 🔧 开源项目
# 5. 每条资讯都要给出重要性评分：★☆☆☆☆ 到 ★★★★★，并写一句 "为什么重要"
# 6. 重要性评分参考：是否来自一手来源、是否影响开发者/产品/产业、是否可立即试用、是否代表趋势变化
# 7. 每条资讯用 2-3 句话总结，保留关键信息（谁、做了什么、为什么重要）
# 8. 在末尾加一段 "今日观察"（3-5 句话），点评今天 AI 领域的整体动态
# 9. 所有内容必须基于提供的原始素材，不要编造
# 10. 输出格式为 Markdown
# 11. 用中文输出，专有名词保留英文

# 每条资讯请使用这个格式：
# - **标题**：一句话摘要。
#   - 重要性：★★★★☆ / 5
#   - 为什么重要：说明对开发者、产品、研究或产业的影响。
#   - 来源：[Source Name](URL)
# """


# def format_raw_content(data):
#     """Format fetched data into a text block for the AI."""
#     sections = []

#     if data.get("news"):
#         sections.append("=== 新闻资讯 ===")
#         for item in data["news"]:
#             sections.append(
#                 f"[{item['source']}] {item['title']}\n"
#                 f"URL: {item['url']}\n"
#                 f"Published: {item.get('published') or 'unknown'}\n"
#                 f"Importance hint: {item.get('importance_hint', 3)}/5\n"
#                 f"{item['summary']}\n"
#             )

#     if data.get("papers"):
#         sections.append("=== 学术论文 ===")
#         for item in data["papers"]:
#             sections.append(
#                 f"[{item['source']}] {item['title']}\n"
#                 f"URL: {item['url']}\n"
#                 f"Published: {item.get('published') or 'unknown'}\n"
#                 f"Importance hint: {item.get('importance_hint', 3)}/5\n"
#                 f"{item['summary']}\n"
#             )

#     if data.get("projects"):
#         sections.append("=== 开源项目 ===")
#         for item in data["projects"]:
#             sections.append(
#                 f"[{item['source']}] {item['title']}\n"
#                 f"URL: {item['url']}\n"
#                 f"Importance hint: {item.get('importance_hint', 3)}/5\n"
#                 f"{item['summary']}\n"
#             )

#     return "\n".join(sections)


# def summarize(data, date_str):
#     """Generate daily digest via OpenAI-compatible API (DeepSeek by default)."""


#     api_key = os.environ.get("API_KEY")
#     if not api_key:
#         raise ValueError("API_KEY environment variable is required")

#     # 👇 新增：读取 AI 提供商
#     provider = os.environ.get("AI_PROVIDER", "deepseek")  # 默认 deepseek


#     # base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
#     # model = os.environ.get("API_MODEL", "deepseek-chat")

#     raw_content = format_raw_content(data)
#     if not raw_content.strip():
#         return f"# AI Daily Digest - {date_str}\n\n> No content fetched today.\n"

#     user_prompt = f"""今天是 {date_str}。

# 以下是今天收集到的 AI 领域原始资讯，请整理成每日简报。
# 请优先选择重要性高、来源可靠、对 AI builder 有实际参考价值的内容：

# {raw_content}"""

#     # url = f"{base_url}/chat/completions"
#     # 👇 如果是 Gemini，走 Google 的 SDK
#     if provider == "gemini":
#         return _summarize_with_gemini(api_key, user_prompt, date_str)

#     # 👇 原有 DeepSeek 逻辑保留不变
#     base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
#     model = os.environ.get("API_MODEL", "deepseek-chat")

#     url = f"{base_url}/chat/completions"

#     headers = {
#         "Authorization": f"Bearer {api_key}",
#         "Content-Type": "application/json",
#     }
#     payload = {
#         "model": model,
#         "messages": [
#             {"role": "system", "content": SYSTEM_PROMPT},
#             {"role": "user", "content": user_prompt},
#         ],
#         "temperature": 0.7,
#         "max_tokens": 4096,
#     }

#     print(f"Calling {model}...")
#     resp = requests.post(url, headers=headers, json=payload, timeout=120)
#     resp.raise_for_status()

#     result = resp.json()
#     text = result["choices"][0]["message"]["content"]

#     markdown = f"""# AI Daily Digest - {date_str}

# {text}

# ---
# *Generated by AI Daily Digest using {model}*
# """
#     return markdown


# # 👇 新增：Gemini 调用函数（放在文件末尾就行）
# def _summarize_with_gemini(api_key, user_prompt, date_str):
#     import google.generativeai as genai
#     genai.configure(api_key=api_key)

#     model = genai.GenerativeModel(
#         'gemini-2.5-flash',  # 最新免费模型
#         system_instruction=SYSTEM_PROMPT  # 复用你已有的系统提示
#     )
#     print("Calling Gemini 2.5 Flash...")
#     response = model.generate_content(user_prompt)
#     text = response.text

#     markdown = f"""# AI Daily Digest - {date_str}

# {text}

# ---
# *Generated by AI Daily Digest using Gemini 2.5 Flash*
# """
#     return markdown


""" AI summarization - supports Gemini and DeepSeek (via OpenAI-compatible API). """
import os
import json
import requests

SYSTEM_PROMPT = """你是一个专业的 AI 行业资讯编辑。你的任务是将收集到的原始 AI 资讯整理成一份高质量的每日简报。
要求：
1. 从提供的原始内容中筛选出最有价值的 10-15 条资讯
2. 去除重复和低质量内容
3. 每条资讯必须保留原文链接，不能省略 URL
4. 按类别分组： 行业新闻 / 重要论文 / 开源项目
5. 每条资讯都要给出重要性评分：★☆☆☆☆ 到 ★★★★★，并写一句 "为什么重要"
6. 重要性评分参考：是否来自一手来源、是否影响开发者/产品/产业、是否可立即试用、是否代表趋势变化
7. 每条资讯用 2-3 句话总结，保留关键信息（谁、做了什么、为什么重要）
8. 在末尾加一段 "今日观察"（3-5 句话），点评今天 AI 领域的整体动态
9. 所有内容必须基于提供的原始素材，不要编造
10. 输出格式为 Markdown
11. 用中文输出，专有名词保留英文
每条资讯请使用这个格式：
- **标题**：一句话摘要。
- 重要性：★★★★☆ / 5
- 为什么重要：说明对开发者、产品、研究或产业的影响。
- 来源：[Source Name](URL)
"""

def format_raw_content(data):
    """Format fetched data into a text block for the AI."""
    sections = []
    if data.get("news"):
        sections.append("=== 新闻资讯 ===")
        for item in data["news"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )
    if data.get("papers"):
        sections.append("=== 学术论文 ===")
        for item in data["papers"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Published: {item.get('published') or 'unknown'}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )
    if data.get("projects"):
        sections.append("=== 开源项目 ===")
        for item in data["projects"]:
            sections.append(
                f"[{item['source']}] {item['title']}\n"
                f"URL: {item['url']}\n"
                f"Importance hint: {item.get('importance_hint', 3)}/5\n"
                f"{item['summary']}\n"
            )
    return "\n".join(sections)

def summarize_with_gemini(api_key, model, prompt):
    """Call Google Gemini API."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    headers = {"Content-Type": "application/json"}
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
    }
    resp = requests.post(url, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()
    result = resp.json()
    # Gemini response structure: candidates[0].content.parts[0].text
    return result["candidates"][0]["content"]["parts"][0]["text"]

def summarize(data, date_str):
    """Generate daily digest via AI. Uses Gemini or DeepSeek."""
    api_key = os.environ.get("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable is required")

    provider = os.environ.get("AI_PROVIDER", "deepseek")
    model = os.environ.get("API_MODEL", "deepseek-chat")

    raw_content = format_raw_content(data)
    if not raw_content.strip():
        return f"# AI Daily Digest - {date_str}\n\n> No content fetched today.\n"

    user_prompt = f"""今天是 {date_str}。

以下是今天收集到的 AI 领域原始资讯，请整理成每日简报。
请优先选择重要性高、来源可靠、对 AI builder 有实际参考价值的内容：

{raw_content}"""

    full_prompt = f"{SYSTEM_PROMPT}\n\n{user_prompt}"

    if provider == "gemini":
        text = summarize_with_gemini(api_key, model, prompt)
    else:
        base_url = os.environ.get("API_BASE_URL", "https://api.deepseek.com")
        url = f"{base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.7,
            "max_tokens": 4096,
        }
        print(f"Calling {model}...")
        resp = requests.post(url, headers=headers, json=payload, timeout=120)
        resp.raise_for_status()
        result = resp.json()
        text = result["choices"][0]["message"]["content"]

    markdown = f"""# AI Daily Digest - {date_str}

{text}

---
*Generated by AI Daily Digest using {model}*
"""
    return markdown